config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :set_note, only: [:show, :update, :destroy, :edit]

  def index
    @notes = Note.all

  end

  def show
    # before_action
  end

  def new
    @note = Note.new
    render partial: 'form'
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path
    else
      render :new
    end

  end

  def edit
    # before_action
    render partial: 'form'

  end

  def update
    # before_action

    if @note.update(note_params)
      redirect_to notes_path
    else
      render :edit
    end

  end

  def destroy
    # before_action
    @note.destroy
    redirect_to notes_path

  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:name, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #00BFFF;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 20px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4169E1;
  color: white;
}
</style>

  <body>
    <div class="topnav">
      <a class="active" href="<%= notes_path %>">Home</a>
      <a href="<%= new_note_path %>">Create New Note</a>
    </div>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<h1><%= @note.id ? 'Edit Note' : 'Create New Note' %></h1>
<%= form_for @note do |n| %>
<p>
  <%= n.label :name %>
  <%= n.text_field :name, required: true %>
</p>

  <p>
  <%= n.label :body%>
  <%= n.text_area :body, required: true %>
 </p> 

  <%= n.submit %>
  <% end %>

app/views/notes/index.html.erb
<h1>Post It Notes and To-Do Items</h1>
<% @notes.each do |n| %>
  <ul>
<%= link_to n.name, note_path(n) %>
<%= link_to 'Edit', edit_note_path(n) %>
<%= link_to 'Delete', n, method: :delete  %>
</ul>
<% end %>

app/views/notes/show.html.erb
<h1><%= @note.name %></h1>
<p><%= @note.body %></p>
<p><%= link_to 'Back', notes_path %></p>